version: '3'

services:
  client:
    image: abeeshs/crm-client:latest 
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8000

  server:
    image: abeeshs/crm-server:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://database:27017/mernapp
      - ORT=8000
      - NODE_ENV=development
      - JWT_SECRET=crmproject123
      - EMAIL=abiabeesh007@gmail.com
      - PASSWORD=judrrgeuaeqdlxsv
      - ACCESS_KEY=AKIAXWMS4C4BGW5KWNTL
      - ACCESS_SECRET=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
      - REGION=ap-south-1
      - BUCKET=stezgabucket
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

